# Generated by Django 3.0.8 on 2020-08-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubNetwork', '0002_auto_20200801_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=1250),
        ),
        migrations.AlterField(
            model_name='repo',
            name='descriptionRepoPost',
            field=models.CharField(max_length=1250),
        ),
    ]
